import type { CSSProperties } from "react";

export const emailBrand = {
  cream: "#F7F2EA",
  paperDeep: "#ECE5D8",
  workSurface: "#F8F4ED",
  paperEdge: "#DCD5C8",
  goldSoft: "#F7EDE0",
  ink: "#1C1A17",
  inkPanel: "#2C2A26",
  muted: "#6B655D",
  signal: "#F76A16",
  sans:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
  mono:
    '"JetBrains Mono", "SFMono-Regular", Menlo, Consolas, "Liberation Mono", monospace',
} as const;

export const emailStyles = {
  main: {
    backgroundColor: emailBrand.cream,
    fontFamily: emailBrand.sans,
    margin: 0,
    padding: "32px 0",
  },
  container: {
    maxWidth: "560px",
    margin: "0 auto",
    padding: "0 16px",
  },
  wideContainer: {
    maxWidth: "640px",
    margin: "0 auto",
    padding: "0 16px",
  },
  card: {
    backgroundColor: emailBrand.workSurface,
    border: `1px solid ${emailBrand.paperEdge}`,
    borderRadius: "12px",
    overflow: "hidden",
  },
  headerBar: {
    backgroundColor: emailBrand.ink,
    padding: "24px 32px",
  },
  brandText: {
    color: emailBrand.workSurface,
    fontSize: "16px",
    fontWeight: 600,
    letterSpacing: "0.01em",
    margin: 0,
  },
  body: {
    padding: "32px",
  },
  eyebrow: {
    color: emailBrand.signal,
    fontFamily: emailBrand.sans,
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.18em",
    lineHeight: 1.25,
    margin: "0 0 12px",
    textTransform: "uppercase",
  },
  eyebrowMuted: {
    color: emailBrand.muted,
    fontFamily: emailBrand.sans,
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.18em",
    lineHeight: 1.25,
    margin: "0 0 12px",
    textTransform: "uppercase",
  },
  h1: {
    color: emailBrand.ink,
    fontSize: "28px",
    fontWeight: 650,
    letterSpacing: "-0.01em",
    lineHeight: 1.16,
    margin: "0 0 18px",
  },
  h2: {
    color: emailBrand.ink,
    fontSize: "21px",
    fontWeight: 650,
    letterSpacing: "-0.01em",
    lineHeight: 1.2,
    margin: "0 0 12px",
  },
  text: {
    color: emailBrand.ink,
    fontSize: "15px",
    lineHeight: 1.6,
    margin: "0 0 16px",
  },
  mutedText: {
    color: emailBrand.muted,
    fontSize: "13px",
    lineHeight: 1.55,
    margin: "0 0 14px",
  },
  button: {
    backgroundColor: emailBrand.ink,
    borderRadius: "8px",
    color: emailBrand.workSurface,
    display: "inline-block",
    fontSize: "14px",
    fontWeight: 650,
    padding: "14px 24px",
    textDecoration: "none",
  },
  link: {
    color: emailBrand.signal,
    textDecoration: "underline",
  },
  hr: {
    borderColor: emailBrand.paperEdge,
    margin: "26px 0 16px",
  },
  footer: {
    color: emailBrand.muted,
    fontSize: "12px",
    lineHeight: 1.55,
    margin: "0",
  },
  codeBlock: {
    backgroundColor: emailBrand.goldSoft,
    border: `1px solid ${emailBrand.paperEdge}`,
    borderRadius: "8px",
    color: emailBrand.ink,
    fontFamily: emailBrand.mono,
    fontSize: "26px",
    fontWeight: 700,
    letterSpacing: "0.2em",
    lineHeight: 1.2,
    margin: "0 0 22px",
    padding: "16px 18px",
    textAlign: "center",
  },
  inset: {
    backgroundColor: emailBrand.goldSoft,
    borderLeft: `3px solid ${emailBrand.signal}`,
    borderRadius: "8px",
    marginTop: "16px",
    padding: "13px 15px",
  },
  pre: {
    backgroundColor: emailBrand.goldSoft,
    border: `1px solid ${emailBrand.paperEdge}`,
    borderRadius: "8px",
    color: emailBrand.ink,
    fontFamily: emailBrand.mono,
    fontSize: "12.5px",
    lineHeight: 1.55,
    margin: 0,
    padding: "14px 16px",
    whiteSpace: "pre-wrap",
  },
} satisfies Record<string, CSSProperties>;
