/**
 * Schedule Intelligence — Build Mode DEMO fixture (scaffold only).
 *
 * Deterministic, internal-only sample DraftSchedule used to prove the
 * Build Mode workspace can render a draft CPM artifact before live AI
 * generation exists.
 *
 * This is NOT AI output. It is hand-written scaffold data clearly labeled
 * as a demo. It must never be persisted, never be applied to a live
 * Schedule, and never participate in calculateSchedule. See
 * docs/schedule-intelligence-ai-spec.md §5, §9.
 */

import {
  createEmptyChangeSet,
  type DraftSchedule,
  type ProposedChange,
  type ProposedChangeSet,
} from "./intel-build";

const DEMO_NOW = "2026-01-15T00:00:00.000Z";

/**
 * Demo draft: small commercial tenant fit-out (~8,400 sf, single floor).
 * Hand-authored — not produced by any model.
 */
export function buildDemoDraftSchedule(): DraftSchedule {
  return {
    version: 1,
    id: "demo-draft-fitout-01",
    name: "DEMO — 8,400 sf Tenant Fit-Out",
    source: "manual_prompt",
    status: "draft",
    inputText:
      "Demo fixture: 8,400 sf single-floor commercial tenant fit-out. " +
      "Demo data only — not generated by AI.",
    wbs: [
      { id: "w-pre", code: "1", name: "Preconstruction" },
      { id: "w-demo", code: "2", name: "Demolition" },
      { id: "w-rough", code: "3", name: "Rough-In" },
      { id: "w-finish", code: "4", name: "Finishes" },
      { id: "w-close", code: "5", name: "Closeout" },
    ],
    activities: [
      { id: "a-permit", name: "Permit & Mobilize", wbsId: "w-pre", durationDays: 5 },
      { id: "a-demo", name: "Selective Demolition", wbsId: "w-demo", durationDays: 4 },
      { id: "a-frame", name: "Metal Stud Framing", wbsId: "w-rough", durationDays: 6 },
      { id: "a-mep", name: "MEP Rough-In", wbsId: "w-rough", durationDays: 8, assumed: true },
      { id: "a-insp1", name: "Rough-In Inspection", wbsId: "w-rough", durationDays: 1, isMilestone: true },
      { id: "a-drywall", name: "Drywall & Tape", wbsId: "w-finish", durationDays: 7 },
      { id: "a-paint", name: "Paint", wbsId: "w-finish", durationDays: 4 },
      { id: "a-floor", name: "Flooring", wbsId: "w-finish", durationDays: 5 },
      { id: "a-trim", name: "Casework & Trim", wbsId: "w-finish", durationDays: 4, assumed: true },
      { id: "a-final", name: "Final Inspection", wbsId: "w-close", durationDays: 1, isMilestone: true },
      { id: "a-punch", name: "Punchlist & Turnover", wbsId: "w-close", durationDays: 3 },
    ],
    relationships: [
      { id: "r1", predecessorId: "a-permit", successorId: "a-demo", type: "FS" },
      { id: "r2", predecessorId: "a-demo", successorId: "a-frame", type: "FS" },
      { id: "r3", predecessorId: "a-frame", successorId: "a-mep", type: "SS", lag: 2 },
      { id: "r4", predecessorId: "a-mep", successorId: "a-insp1", type: "FS" },
      { id: "r5", predecessorId: "a-insp1", successorId: "a-drywall", type: "FS" },
      { id: "r6", predecessorId: "a-drywall", successorId: "a-paint", type: "FS" },
      { id: "r7", predecessorId: "a-paint", successorId: "a-floor", type: "FS" },
      { id: "r8", predecessorId: "a-floor", successorId: "a-trim", type: "FS" },
      { id: "r9", predecessorId: "a-trim", successorId: "a-final", type: "FS" },
      { id: "r10", predecessorId: "a-final", successorId: "a-punch", type: "FS" },
    ],
    milestones: [
      { id: "m1", name: "Rough-In Complete", activityId: "a-insp1" },
      { id: "m2", name: "Substantial Completion", activityId: "a-final" },
    ],
    assumptions: [
      { id: "as1", label: "MEP rough-in duration assumed 8 days", detail: "Based on typical 8k sf TI; confirm with subs." },
      { id: "as2", label: "Owner-furnished casework arrives before trim start" },
      { id: "as3", label: "Single shift, Mon–Fri calendar" },
    ],
    questions: [
      { id: "q1", question: "Is fire-sprinkler retrofit in scope?" },
      { id: "q2", question: "Is there a hard substantial-completion date?" },
      { id: "q3", question: "Are inspections owner-scheduled or GC-scheduled?" },
    ],
    warnings: [
      { id: "wn1", severity: "info", message: "Demo fixture — not produced by an AI model." },
      { id: "wn2", severity: "warn", message: "Durations are assumed; review before approval." },
    ],
    createdAt: DEMO_NOW,
    updatedAt: DEMO_NOW,
  };
}

/**
 * Derive a non-committable preview ProposedChangeSet from a draft. Used
 * only to render counts and the committable gate. No commit logic.
 */
export function buildPreviewChangeSet(draft: DraftSchedule): ProposedChangeSet {
  const cs = createEmptyChangeSet({
    id: `preview-${draft.id}`,
    title: `Preview — ${draft.name}`,
    draftId: draft.id,
    now: () => draft.updatedAt,
  });

  const changes: ProposedChange[] = [];

  for (const a of draft.activities) {
    if (a.isMilestone) {
      changes.push({
        id: `ch-ms-${a.id}`,
        kind: "add_milestone",
        rationale: `Milestone from draft: ${a.name}`,
        draftRefId: a.id,
        payload: { name: a.name, activityId: a.id },
      });
    } else {
      changes.push({
        id: `ch-act-${a.id}`,
        kind: "add_activity",
        rationale: `New activity from draft: ${a.name}`,
        draftRefId: a.id,
        payload: {
          name: a.name,
          durationDays: a.durationDays ?? 1,
          wbs: a.wbsId,
        },
      });
    }
  }

  for (const r of draft.relationships) {
    changes.push({
      id: `ch-rel-${r.id}`,
      kind: "add_relationship",
      rationale: `Logic from draft: ${r.predecessorId} → ${r.successorId}`,
      draftRefId: r.id,
      payload: {
        from: r.predecessorId,
        to: r.successorId,
        type: r.type,
        lag: r.lag,
      },
    });
  }

  cs.changes = changes;
  // status intentionally stays "draft" so isChangeSetCommittable === false
  return cs;
}

export interface ChangeSetCounts {
  addActivity: number;
  addRelationship: number;
  addMilestone: number;
  total: number;
}

export function countChangeSet(cs: ProposedChangeSet): ChangeSetCounts {
  let addActivity = 0;
  let addRelationship = 0;
  let addMilestone = 0;
  for (const c of cs.changes) {
    if (c.kind === "add_activity") addActivity++;
    else if (c.kind === "add_relationship") addRelationship++;
    else if (c.kind === "add_milestone") addMilestone++;
  }
  return {
    addActivity,
    addRelationship,
    addMilestone,
    total: cs.changes.length,
  };
}
