/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithMarshallRouteImport } from './routes/work-with-marshall'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FieldToolsRouteImport } from './routes/field-tools'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AosRouteImport } from './routes/aos'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskIndexRouteImport } from './routes/ask.index'
import { Route as ToolsOwnerDependencyRouteImport } from './routes/tools.owner-dependency'
import { Route as ToolsGrowthConstraintRouteImport } from './routes/tools.growth-constraint'
import { Route as AskNewRouteImport } from './routes/ask.new'
import { Route as AskThreadIdRouteImport } from './routes/ask.$threadId'
import { Route as ApiAskRouteImport } from './routes/api/ask'

const WorkWithMarshallRoute = WorkWithMarshallRouteImport.update({
  id: '/work-with-marshall',
  path: '/work-with-marshall',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldToolsRoute = FieldToolsRouteImport.update({
  id: '/field-tools',
  path: '/field-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AosRoute = AosRouteImport.update({
  id: '/aos',
  path: '/aos',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskIndexRoute = AskIndexRouteImport.update({
  id: '/ask/',
  path: '/ask/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOwnerDependencyRoute = ToolsOwnerDependencyRouteImport.update({
  id: '/owner-dependency',
  path: '/owner-dependency',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsGrowthConstraintRoute = ToolsGrowthConstraintRouteImport.update({
  id: '/growth-constraint',
  path: '/growth-constraint',
  getParentRoute: () => ToolsRoute,
} as any)
const AskNewRoute = AskNewRouteImport.update({
  id: '/ask/new',
  path: '/ask/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AskThreadIdRoute = AskThreadIdRouteImport.update({
  id: '/ask/$threadId',
  path: '/ask/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/aos': typeof AosRoute
  '/calls': typeof CallsRoute
  '/community': typeof CommunityRoute
  '/field-tools': typeof FieldToolsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/vault': typeof VaultRoute
  '/work-with-marshall': typeof WorkWithMarshallRoute
  '/api/ask': typeof ApiAskRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/new': typeof AskNewRoute
  '/tools/growth-constraint': typeof ToolsGrowthConstraintRoute
  '/tools/owner-dependency': typeof ToolsOwnerDependencyRoute
  '/ask/': typeof AskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/aos': typeof AosRoute
  '/calls': typeof CallsRoute
  '/community': typeof CommunityRoute
  '/field-tools': typeof FieldToolsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/vault': typeof VaultRoute
  '/work-with-marshall': typeof WorkWithMarshallRoute
  '/api/ask': typeof ApiAskRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/new': typeof AskNewRoute
  '/tools/growth-constraint': typeof ToolsGrowthConstraintRoute
  '/tools/owner-dependency': typeof ToolsOwnerDependencyRoute
  '/ask': typeof AskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/aos': typeof AosRoute
  '/calls': typeof CallsRoute
  '/community': typeof CommunityRoute
  '/field-tools': typeof FieldToolsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/vault': typeof VaultRoute
  '/work-with-marshall': typeof WorkWithMarshallRoute
  '/api/ask': typeof ApiAskRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/new': typeof AskNewRoute
  '/tools/growth-constraint': typeof ToolsGrowthConstraintRoute
  '/tools/owner-dependency': typeof ToolsOwnerDependencyRoute
  '/ask/': typeof AskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/aos'
    | '/calls'
    | '/community'
    | '/field-tools'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/templates'
    | '/tools'
    | '/vault'
    | '/work-with-marshall'
    | '/api/ask'
    | '/ask/$threadId'
    | '/ask/new'
    | '/tools/growth-constraint'
    | '/tools/owner-dependency'
    | '/ask/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/aos'
    | '/calls'
    | '/community'
    | '/field-tools'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/templates'
    | '/tools'
    | '/vault'
    | '/work-with-marshall'
    | '/api/ask'
    | '/ask/$threadId'
    | '/ask/new'
    | '/tools/growth-constraint'
    | '/tools/owner-dependency'
    | '/ask'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/aos'
    | '/calls'
    | '/community'
    | '/field-tools'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/templates'
    | '/tools'
    | '/vault'
    | '/work-with-marshall'
    | '/api/ask'
    | '/ask/$threadId'
    | '/ask/new'
    | '/tools/growth-constraint'
    | '/tools/owner-dependency'
    | '/ask/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AosRoute: typeof AosRoute
  CallsRoute: typeof CallsRoute
  CommunityRoute: typeof CommunityRoute
  FieldToolsRoute: typeof FieldToolsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  TemplatesRoute: typeof TemplatesRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  VaultRoute: typeof VaultRoute
  WorkWithMarshallRoute: typeof WorkWithMarshallRoute
  ApiAskRoute: typeof ApiAskRoute
  AskThreadIdRoute: typeof AskThreadIdRoute
  AskNewRoute: typeof AskNewRoute
  AskIndexRoute: typeof AskIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-marshall': {
      id: '/work-with-marshall'
      path: '/work-with-marshall'
      fullPath: '/work-with-marshall'
      preLoaderRoute: typeof WorkWithMarshallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-tools': {
      id: '/field-tools'
      path: '/field-tools'
      fullPath: '/field-tools'
      preLoaderRoute: typeof FieldToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aos': {
      id: '/aos'
      path: '/aos'
      fullPath: '/aos'
      preLoaderRoute: typeof AosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/': {
      id: '/ask/'
      path: '/ask'
      fullPath: '/ask/'
      preLoaderRoute: typeof AskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/owner-dependency': {
      id: '/tools/owner-dependency'
      path: '/owner-dependency'
      fullPath: '/tools/owner-dependency'
      preLoaderRoute: typeof ToolsOwnerDependencyRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/growth-constraint': {
      id: '/tools/growth-constraint'
      path: '/growth-constraint'
      fullPath: '/tools/growth-constraint'
      preLoaderRoute: typeof ToolsGrowthConstraintRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/ask/new': {
      id: '/ask/new'
      path: '/ask/new'
      fullPath: '/ask/new'
      preLoaderRoute: typeof AskNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/$threadId': {
      id: '/ask/$threadId'
      path: '/ask/$threadId'
      fullPath: '/ask/$threadId'
      preLoaderRoute: typeof AskThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolsRouteChildren {
  ToolsGrowthConstraintRoute: typeof ToolsGrowthConstraintRoute
  ToolsOwnerDependencyRoute: typeof ToolsOwnerDependencyRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsGrowthConstraintRoute: ToolsGrowthConstraintRoute,
  ToolsOwnerDependencyRoute: ToolsOwnerDependencyRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AosRoute: AosRoute,
  CallsRoute: CallsRoute,
  CommunityRoute: CommunityRoute,
  FieldToolsRoute: FieldToolsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  TemplatesRoute: TemplatesRoute,
  ToolsRoute: ToolsRouteWithChildren,
  VaultRoute: VaultRoute,
  WorkWithMarshallRoute: WorkWithMarshallRoute,
  ApiAskRoute: ApiAskRoute,
  AskThreadIdRoute: AskThreadIdRoute,
  AskNewRoute: AskNewRoute,
  AskIndexRoute: AskIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
