/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithMarshallRouteImport } from './routes/work-with-marshall'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReplaysRouteImport } from './routes/replays'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FieldToolsRouteImport } from './routes/field-tools'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskIndexRouteImport } from './routes/ask.index'
import { Route as AosIndexRouteImport } from './routes/aos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToolsOwnerDependencyRouteImport } from './routes/tools.owner-dependency'
import { Route as ToolsGrowthConstraintRouteImport } from './routes/tools.growth-constraint'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AskNewRouteImport } from './routes/ask.new'
import { Route as AskThreadIdRouteImport } from './routes/ask.$threadId'
import { Route as ApiSopDraftRouteImport } from './routes/api/sop-draft'
import { Route as ApiSopBacklogRouteImport } from './routes/api/sop-backlog'
import { Route as ApiOwnerPlaysRouteImport } from './routes/api/owner-plays'
import { Route as ApiContractScanRouteImport } from './routes/api/contract-scan'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as AosLinkRouteImport } from './routes/aos.link'
import { Route as AdminTopicsRouteImport } from './routes/admin.topics'
import { Route as AdminMigrateRouteImport } from './routes/admin.migrate'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminAnnounceRouteImport } from './routes/admin.announce'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'

const WorkWithMarshallRoute = WorkWithMarshallRouteImport.update({
  id: '/work-with-marshall',
  path: '/work-with-marshall',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaysRoute = ReplaysRouteImport.update({
  id: '/replays',
  path: '/replays',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldToolsRoute = FieldToolsRouteImport.update({
  id: '/field-tools',
  path: '/field-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskIndexRoute = AskIndexRouteImport.update({
  id: '/ask/',
  path: '/ask/',
  getParentRoute: () => rootRouteImport,
} as any)
const AosIndexRoute = AosIndexRouteImport.update({
  id: '/aos/',
  path: '/aos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOwnerDependencyRoute = ToolsOwnerDependencyRouteImport.update({
  id: '/owner-dependency',
  path: '/owner-dependency',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsGrowthConstraintRoute = ToolsGrowthConstraintRouteImport.update({
  id: '/growth-constraint',
  path: '/growth-constraint',
  getParentRoute: () => ToolsRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AskNewRoute = AskNewRouteImport.update({
  id: '/ask/new',
  path: '/ask/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AskThreadIdRoute = AskThreadIdRouteImport.update({
  id: '/ask/$threadId',
  path: '/ask/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSopDraftRoute = ApiSopDraftRouteImport.update({
  id: '/api/sop-draft',
  path: '/api/sop-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSopBacklogRoute = ApiSopBacklogRouteImport.update({
  id: '/api/sop-backlog',
  path: '/api/sop-backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOwnerPlaysRoute = ApiOwnerPlaysRouteImport.update({
  id: '/api/owner-plays',
  path: '/api/owner-plays',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContractScanRoute = ApiContractScanRouteImport.update({
  id: '/api/contract-scan',
  path: '/api/contract-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AosLinkRoute = AosLinkRouteImport.update({
  id: '/aos/link',
  path: '/aos/link',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTopicsRoute = AdminTopicsRouteImport.update({
  id: '/admin/topics',
  path: '/admin/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigrateRoute = AdminMigrateRouteImport.update({
  id: '/admin/migrate',
  path: '/admin/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/admin/library',
  path: '/admin/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnounceRoute = AdminAnnounceRouteImport.update({
  id: '/admin/announce',
  path: '/admin/announce',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calls': typeof CallsRoute
  '/community': typeof CommunityRoute
  '/field-tools': typeof FieldToolsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/handbook': typeof HandbookRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/replays': typeof ReplaysRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/vault': typeof VaultRoute
  '/welcome': typeof WelcomeRoute
  '/work-with-marshall': typeof WorkWithMarshallRoute
  '/admin/announce': typeof AdminAnnounceRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/aos/link': typeof AosLinkRoute
  '/api/ask': typeof ApiAskRoute
  '/api/contract-scan': typeof ApiContractScanRoute
  '/api/owner-plays': typeof ApiOwnerPlaysRoute
  '/api/sop-backlog': typeof ApiSopBacklogRoute
  '/api/sop-draft': typeof ApiSopDraftRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/new': typeof AskNewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/tools/growth-constraint': typeof ToolsGrowthConstraintRoute
  '/tools/owner-dependency': typeof ToolsOwnerDependencyRoute
  '/admin/': typeof AdminIndexRoute
  '/aos/': typeof AosIndexRoute
  '/ask/': typeof AskIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calls': typeof CallsRoute
  '/community': typeof CommunityRoute
  '/field-tools': typeof FieldToolsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/handbook': typeof HandbookRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/replays': typeof ReplaysRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/vault': typeof VaultRoute
  '/welcome': typeof WelcomeRoute
  '/work-with-marshall': typeof WorkWithMarshallRoute
  '/admin/announce': typeof AdminAnnounceRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/aos/link': typeof AosLinkRoute
  '/api/ask': typeof ApiAskRoute
  '/api/contract-scan': typeof ApiContractScanRoute
  '/api/owner-plays': typeof ApiOwnerPlaysRoute
  '/api/sop-backlog': typeof ApiSopBacklogRoute
  '/api/sop-draft': typeof ApiSopDraftRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/new': typeof AskNewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/tools/growth-constraint': typeof ToolsGrowthConstraintRoute
  '/tools/owner-dependency': typeof ToolsOwnerDependencyRoute
  '/admin': typeof AdminIndexRoute
  '/aos': typeof AosIndexRoute
  '/ask': typeof AskIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calls': typeof CallsRoute
  '/community': typeof CommunityRoute
  '/field-tools': typeof FieldToolsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/handbook': typeof HandbookRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/replays': typeof ReplaysRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/vault': typeof VaultRoute
  '/welcome': typeof WelcomeRoute
  '/work-with-marshall': typeof WorkWithMarshallRoute
  '/admin/announce': typeof AdminAnnounceRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/aos/link': typeof AosLinkRoute
  '/api/ask': typeof ApiAskRoute
  '/api/contract-scan': typeof ApiContractScanRoute
  '/api/owner-plays': typeof ApiOwnerPlaysRoute
  '/api/sop-backlog': typeof ApiSopBacklogRoute
  '/api/sop-draft': typeof ApiSopDraftRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/new': typeof AskNewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/tools/growth-constraint': typeof ToolsGrowthConstraintRoute
  '/tools/owner-dependency': typeof ToolsOwnerDependencyRoute
  '/admin/': typeof AdminIndexRoute
  '/aos/': typeof AosIndexRoute
  '/ask/': typeof AskIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/calls'
    | '/community'
    | '/field-tools'
    | '/forgot-password'
    | '/handbook'
    | '/login'
    | '/onboarding'
    | '/replays'
    | '/reset-password'
    | '/signup'
    | '/templates'
    | '/tools'
    | '/upgrade'
    | '/vault'
    | '/welcome'
    | '/work-with-marshall'
    | '/admin/announce'
    | '/admin/library'
    | '/admin/migrate'
    | '/admin/topics'
    | '/aos/link'
    | '/api/ask'
    | '/api/contract-scan'
    | '/api/owner-plays'
    | '/api/sop-backlog'
    | '/api/sop-draft'
    | '/ask/$threadId'
    | '/ask/new'
    | '/email/unsubscribe'
    | '/tools/growth-constraint'
    | '/tools/owner-dependency'
    | '/admin/'
    | '/aos/'
    | '/ask/'
    | '/lovable/email/suppression'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/calls'
    | '/community'
    | '/field-tools'
    | '/forgot-password'
    | '/handbook'
    | '/login'
    | '/onboarding'
    | '/replays'
    | '/reset-password'
    | '/signup'
    | '/templates'
    | '/tools'
    | '/upgrade'
    | '/vault'
    | '/welcome'
    | '/work-with-marshall'
    | '/admin/announce'
    | '/admin/library'
    | '/admin/migrate'
    | '/admin/topics'
    | '/aos/link'
    | '/api/ask'
    | '/api/contract-scan'
    | '/api/owner-plays'
    | '/api/sop-backlog'
    | '/api/sop-draft'
    | '/ask/$threadId'
    | '/ask/new'
    | '/email/unsubscribe'
    | '/tools/growth-constraint'
    | '/tools/owner-dependency'
    | '/admin'
    | '/aos'
    | '/ask'
    | '/lovable/email/suppression'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/calls'
    | '/community'
    | '/field-tools'
    | '/forgot-password'
    | '/handbook'
    | '/login'
    | '/onboarding'
    | '/replays'
    | '/reset-password'
    | '/signup'
    | '/templates'
    | '/tools'
    | '/upgrade'
    | '/vault'
    | '/welcome'
    | '/work-with-marshall'
    | '/admin/announce'
    | '/admin/library'
    | '/admin/migrate'
    | '/admin/topics'
    | '/aos/link'
    | '/api/ask'
    | '/api/contract-scan'
    | '/api/owner-plays'
    | '/api/sop-backlog'
    | '/api/sop-draft'
    | '/ask/$threadId'
    | '/ask/new'
    | '/email/unsubscribe'
    | '/tools/growth-constraint'
    | '/tools/owner-dependency'
    | '/admin/'
    | '/aos/'
    | '/ask/'
    | '/lovable/email/suppression'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CallsRoute: typeof CallsRoute
  CommunityRoute: typeof CommunityRoute
  FieldToolsRoute: typeof FieldToolsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HandbookRoute: typeof HandbookRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ReplaysRoute: typeof ReplaysRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TemplatesRoute: typeof TemplatesRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UpgradeRoute: typeof UpgradeRoute
  VaultRoute: typeof VaultRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkWithMarshallRoute: typeof WorkWithMarshallRoute
  AdminAnnounceRoute: typeof AdminAnnounceRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminMigrateRoute: typeof AdminMigrateRoute
  AdminTopicsRoute: typeof AdminTopicsRoute
  AosLinkRoute: typeof AosLinkRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiContractScanRoute: typeof ApiContractScanRoute
  ApiOwnerPlaysRoute: typeof ApiOwnerPlaysRoute
  ApiSopBacklogRoute: typeof ApiSopBacklogRoute
  ApiSopDraftRoute: typeof ApiSopDraftRoute
  AskThreadIdRoute: typeof AskThreadIdRoute
  AskNewRoute: typeof AskNewRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AosIndexRoute: typeof AosIndexRoute
  AskIndexRoute: typeof AskIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-marshall': {
      id: '/work-with-marshall'
      path: '/work-with-marshall'
      fullPath: '/work-with-marshall'
      preLoaderRoute: typeof WorkWithMarshallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replays': {
      id: '/replays'
      path: '/replays'
      fullPath: '/replays'
      preLoaderRoute: typeof ReplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-tools': {
      id: '/field-tools'
      path: '/field-tools'
      fullPath: '/field-tools'
      preLoaderRoute: typeof FieldToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/': {
      id: '/ask/'
      path: '/ask'
      fullPath: '/ask/'
      preLoaderRoute: typeof AskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aos/': {
      id: '/aos/'
      path: '/aos'
      fullPath: '/aos/'
      preLoaderRoute: typeof AosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/owner-dependency': {
      id: '/tools/owner-dependency'
      path: '/owner-dependency'
      fullPath: '/tools/owner-dependency'
      preLoaderRoute: typeof ToolsOwnerDependencyRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/growth-constraint': {
      id: '/tools/growth-constraint'
      path: '/growth-constraint'
      fullPath: '/tools/growth-constraint'
      preLoaderRoute: typeof ToolsGrowthConstraintRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/new': {
      id: '/ask/new'
      path: '/ask/new'
      fullPath: '/ask/new'
      preLoaderRoute: typeof AskNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/$threadId': {
      id: '/ask/$threadId'
      path: '/ask/$threadId'
      fullPath: '/ask/$threadId'
      preLoaderRoute: typeof AskThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sop-draft': {
      id: '/api/sop-draft'
      path: '/api/sop-draft'
      fullPath: '/api/sop-draft'
      preLoaderRoute: typeof ApiSopDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sop-backlog': {
      id: '/api/sop-backlog'
      path: '/api/sop-backlog'
      fullPath: '/api/sop-backlog'
      preLoaderRoute: typeof ApiSopBacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/owner-plays': {
      id: '/api/owner-plays'
      path: '/api/owner-plays'
      fullPath: '/api/owner-plays'
      preLoaderRoute: typeof ApiOwnerPlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contract-scan': {
      id: '/api/contract-scan'
      path: '/api/contract-scan'
      fullPath: '/api/contract-scan'
      preLoaderRoute: typeof ApiContractScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aos/link': {
      id: '/aos/link'
      path: '/aos/link'
      fullPath: '/aos/link'
      preLoaderRoute: typeof AosLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/topics': {
      id: '/admin/topics'
      path: '/admin/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AdminTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migrate': {
      id: '/admin/migrate'
      path: '/admin/migrate'
      fullPath: '/admin/migrate'
      preLoaderRoute: typeof AdminMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/admin/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announce': {
      id: '/admin/announce'
      path: '/admin/announce'
      fullPath: '/admin/announce'
      preLoaderRoute: typeof AdminAnnounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolsRouteChildren {
  ToolsGrowthConstraintRoute: typeof ToolsGrowthConstraintRoute
  ToolsOwnerDependencyRoute: typeof ToolsOwnerDependencyRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsGrowthConstraintRoute: ToolsGrowthConstraintRoute,
  ToolsOwnerDependencyRoute: ToolsOwnerDependencyRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CallsRoute: CallsRoute,
  CommunityRoute: CommunityRoute,
  FieldToolsRoute: FieldToolsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HandbookRoute: HandbookRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ReplaysRoute: ReplaysRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TemplatesRoute: TemplatesRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UpgradeRoute: UpgradeRoute,
  VaultRoute: VaultRoute,
  WelcomeRoute: WelcomeRoute,
  WorkWithMarshallRoute: WorkWithMarshallRoute,
  AdminAnnounceRoute: AdminAnnounceRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminMigrateRoute: AdminMigrateRoute,
  AdminTopicsRoute: AdminTopicsRoute,
  AosLinkRoute: AosLinkRoute,
  ApiAskRoute: ApiAskRoute,
  ApiContractScanRoute: ApiContractScanRoute,
  ApiOwnerPlaysRoute: ApiOwnerPlaysRoute,
  ApiSopBacklogRoute: ApiSopBacklogRoute,
  ApiSopDraftRoute: ApiSopDraftRoute,
  AskThreadIdRoute: AskThreadIdRoute,
  AskNewRoute: AskNewRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  AdminIndexRoute: AdminIndexRoute,
  AosIndexRoute: AosIndexRoute,
  AskIndexRoute: AskIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
