/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithMarshallRouteImport } from './routes/work-with-marshall'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchedulerPreviewRouteImport } from './routes/scheduler-preview'
import { Route as SchedulerPortfolioRouteImport } from './routes/scheduler-portfolio'
import { Route as SchedulerFieldRouteImport } from './routes/scheduler-field'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReplaysRouteImport } from './routes/replays'
import { Route as OverwatchRouteImport } from './routes/overwatch'
import { Route as OperatingPlaybookRouteImport } from './routes/operating-playbook'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HardcoreRouteImport } from './routes/hardcore'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FieldToolsRouteImport } from './routes/field-tools'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskIndexRouteImport } from './routes/ask.index'
import { Route as AosIndexRouteImport } from './routes/aos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToolsOwnerDependencyRouteImport } from './routes/tools.owner-dependency'
import { Route as ToolsGrowthConstraintRouteImport } from './routes/tools.growth-constraint'
import { Route as ToolsCosNavigatorRouteImport } from './routes/tools.cos-navigator'
import { Route as SchedulerProjectIdRouteImport } from './routes/scheduler.$projectId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AskNewRouteImport } from './routes/ask.new'
import { Route as AskThreadIdRouteImport } from './routes/ask.$threadId'
import { Route as ApiSopDraftRouteImport } from './routes/api/sop-draft'
import { Route as ApiSopBacklogRouteImport } from './routes/api/sop-backlog'
import { Route as ApiOwnerPlaysRouteImport } from './routes/api/owner-plays'
import { Route as ApiContractScanRouteImport } from './routes/api/contract-scan'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as AosLinkRouteImport } from './routes/aos.link'
import { Route as AosAddCapacityRouteImport } from './routes/aos.add-capacity'
import { Route as AdminWeeklyMoveRouteImport } from './routes/admin.weekly-move'
import { Route as AdminTopicsRouteImport } from './routes/admin.topics'
import { Route as AdminQaRouteImport } from './routes/admin.qa'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as AdminMigrateRouteImport } from './routes/admin.migrate'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminIntensiveLeadsRouteImport } from './routes/admin.intensive-leads'
import { Route as AdminHandbookRouteImport } from './routes/admin.handbook'
import { Route as AdminEmailApprovalsRouteImport } from './routes/admin.email-approvals'
import { Route as AdminBackfillRouteImport } from './routes/admin.backfill'
import { Route as AdminAnnounceRouteImport } from './routes/admin.announce'
import { Route as ToolsSopEditPacketIdRouteImport } from './routes/tools.sop-edit.$packetId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicAosFpRouteImport } from './routes/api/public/aos-fp'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicAosTierLookupRouteImport } from './routes/api/public/aos/tier-lookup'

const WorkWithMarshallRoute = WorkWithMarshallRouteImport.update({
  id: '/work-with-marshall',
  path: '/work-with-marshall',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerPreviewRoute = SchedulerPreviewRouteImport.update({
  id: '/scheduler-preview',
  path: '/scheduler-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerPortfolioRoute = SchedulerPortfolioRouteImport.update({
  id: '/scheduler-portfolio',
  path: '/scheduler-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerFieldRoute = SchedulerFieldRouteImport.update({
  id: '/scheduler-field',
  path: '/scheduler-field',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaysRoute = ReplaysRouteImport.update({
  id: '/replays',
  path: '/replays',
  getParentRoute: () => rootRouteImport,
} as any)
const OverwatchRoute = OverwatchRouteImport.update({
  id: '/overwatch',
  path: '/overwatch',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatingPlaybookRoute = OperatingPlaybookRouteImport.update({
  id: '/operating-playbook',
  path: '/operating-playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HardcoreRoute = HardcoreRouteImport.update({
  id: '/hardcore',
  path: '/hardcore',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldToolsRoute = FieldToolsRouteImport.update({
  id: '/field-tools',
  path: '/field-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskIndexRoute = AskIndexRouteImport.update({
  id: '/ask/',
  path: '/ask/',
  getParentRoute: () => rootRouteImport,
} as any)
const AosIndexRoute = AosIndexRouteImport.update({
  id: '/aos/',
  path: '/aos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOwnerDependencyRoute = ToolsOwnerDependencyRouteImport.update({
  id: '/owner-dependency',
  path: '/owner-dependency',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsGrowthConstraintRoute = ToolsGrowthConstraintRouteImport.update({
  id: '/growth-constraint',
  path: '/growth-constraint',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCosNavigatorRoute = ToolsCosNavigatorRouteImport.update({
  id: '/cos-navigator',
  path: '/cos-navigator',
  getParentRoute: () => ToolsRoute,
} as any)
const SchedulerProjectIdRoute = SchedulerProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => SchedulerRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AskNewRoute = AskNewRouteImport.update({
  id: '/ask/new',
  path: '/ask/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AskThreadIdRoute = AskThreadIdRouteImport.update({
  id: '/ask/$threadId',
  path: '/ask/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSopDraftRoute = ApiSopDraftRouteImport.update({
  id: '/api/sop-draft',
  path: '/api/sop-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSopBacklogRoute = ApiSopBacklogRouteImport.update({
  id: '/api/sop-backlog',
  path: '/api/sop-backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOwnerPlaysRoute = ApiOwnerPlaysRouteImport.update({
  id: '/api/owner-plays',
  path: '/api/owner-plays',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContractScanRoute = ApiContractScanRouteImport.update({
  id: '/api/contract-scan',
  path: '/api/contract-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AosLinkRoute = AosLinkRouteImport.update({
  id: '/aos/link',
  path: '/aos/link',
  getParentRoute: () => rootRouteImport,
} as any)
const AosAddCapacityRoute = AosAddCapacityRouteImport.update({
  id: '/aos/add-capacity',
  path: '/aos/add-capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWeeklyMoveRoute = AdminWeeklyMoveRouteImport.update({
  id: '/admin/weekly-move',
  path: '/admin/weekly-move',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTopicsRoute = AdminTopicsRouteImport.update({
  id: '/admin/topics',
  path: '/admin/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQaRoute = AdminQaRouteImport.update({
  id: '/admin/qa',
  path: '/admin/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/admin/people',
  path: '/admin/people',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigrateRoute = AdminMigrateRouteImport.update({
  id: '/admin/migrate',
  path: '/admin/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/admin/library',
  path: '/admin/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntensiveLeadsRoute = AdminIntensiveLeadsRouteImport.update({
  id: '/admin/intensive-leads',
  path: '/admin/intensive-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHandbookRoute = AdminHandbookRouteImport.update({
  id: '/admin/handbook',
  path: '/admin/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailApprovalsRoute = AdminEmailApprovalsRouteImport.update({
  id: '/admin/email-approvals',
  path: '/admin/email-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBackfillRoute = AdminBackfillRouteImport.update({
  id: '/admin/backfill',
  path: '/admin/backfill',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnounceRoute = AdminAnnounceRouteImport.update({
  id: '/admin/announce',
  path: '/admin/announce',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSopEditPacketIdRoute = ToolsSopEditPacketIdRouteImport.update({
  id: '/sop-edit/$packetId',
  path: '/sop-edit/$packetId',
  getParentRoute: () => ToolsRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAosFpRoute = ApiPublicAosFpRouteImport.update({
  id: '/api/public/aos-fp',
  path: '/api/public/aos-fp',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAosTierLookupRoute = ApiPublicAosTierLookupRouteImport.update({
  id: '/api/public/aos/tier-lookup',
  path: '/api/public/aos/tier-lookup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calls': typeof CallsRoute
  '/community': typeof CommunityRoute
  '/field-tools': typeof FieldToolsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/handbook': typeof HandbookRoute
  '/hardcore': typeof HardcoreRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/onboarding': typeof OnboardingRoute
  '/operating-playbook': typeof OperatingPlaybookRoute
  '/overwatch': typeof OverwatchRoute
  '/replays': typeof ReplaysRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scheduler': typeof SchedulerRouteWithChildren
  '/scheduler-field': typeof SchedulerFieldRoute
  '/scheduler-portfolio': typeof SchedulerPortfolioRoute
  '/scheduler-preview': typeof SchedulerPreviewRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/vault': typeof VaultRoute
  '/welcome': typeof WelcomeRoute
  '/work-with-marshall': typeof WorkWithMarshallRoute
  '/admin/announce': typeof AdminAnnounceRoute
  '/admin/backfill': typeof AdminBackfillRoute
  '/admin/email-approvals': typeof AdminEmailApprovalsRoute
  '/admin/handbook': typeof AdminHandbookRoute
  '/admin/intensive-leads': typeof AdminIntensiveLeadsRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/admin/weekly-move': typeof AdminWeeklyMoveRoute
  '/aos/add-capacity': typeof AosAddCapacityRoute
  '/aos/link': typeof AosLinkRoute
  '/api/ask': typeof ApiAskRoute
  '/api/contract-scan': typeof ApiContractScanRoute
  '/api/owner-plays': typeof ApiOwnerPlaysRoute
  '/api/sop-backlog': typeof ApiSopBacklogRoute
  '/api/sop-draft': typeof ApiSopDraftRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/new': typeof AskNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/scheduler/$projectId': typeof SchedulerProjectIdRoute
  '/tools/cos-navigator': typeof ToolsCosNavigatorRoute
  '/tools/growth-constraint': typeof ToolsGrowthConstraintRoute
  '/tools/owner-dependency': typeof ToolsOwnerDependencyRoute
  '/admin/': typeof AdminIndexRoute
  '/aos/': typeof AosIndexRoute
  '/ask/': typeof AskIndexRoute
  '/api/public/aos-fp': typeof ApiPublicAosFpRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/tools/sop-edit/$packetId': typeof ToolsSopEditPacketIdRoute
  '/api/public/aos/tier-lookup': typeof ApiPublicAosTierLookupRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calls': typeof CallsRoute
  '/community': typeof CommunityRoute
  '/field-tools': typeof FieldToolsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/handbook': typeof HandbookRoute
  '/hardcore': typeof HardcoreRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/onboarding': typeof OnboardingRoute
  '/operating-playbook': typeof OperatingPlaybookRoute
  '/overwatch': typeof OverwatchRoute
  '/replays': typeof ReplaysRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scheduler': typeof SchedulerRouteWithChildren
  '/scheduler-field': typeof SchedulerFieldRoute
  '/scheduler-portfolio': typeof SchedulerPortfolioRoute
  '/scheduler-preview': typeof SchedulerPreviewRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/vault': typeof VaultRoute
  '/welcome': typeof WelcomeRoute
  '/work-with-marshall': typeof WorkWithMarshallRoute
  '/admin/announce': typeof AdminAnnounceRoute
  '/admin/backfill': typeof AdminBackfillRoute
  '/admin/email-approvals': typeof AdminEmailApprovalsRoute
  '/admin/handbook': typeof AdminHandbookRoute
  '/admin/intensive-leads': typeof AdminIntensiveLeadsRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/admin/weekly-move': typeof AdminWeeklyMoveRoute
  '/aos/add-capacity': typeof AosAddCapacityRoute
  '/aos/link': typeof AosLinkRoute
  '/api/ask': typeof ApiAskRoute
  '/api/contract-scan': typeof ApiContractScanRoute
  '/api/owner-plays': typeof ApiOwnerPlaysRoute
  '/api/sop-backlog': typeof ApiSopBacklogRoute
  '/api/sop-draft': typeof ApiSopDraftRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/new': typeof AskNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/scheduler/$projectId': typeof SchedulerProjectIdRoute
  '/tools/cos-navigator': typeof ToolsCosNavigatorRoute
  '/tools/growth-constraint': typeof ToolsGrowthConstraintRoute
  '/tools/owner-dependency': typeof ToolsOwnerDependencyRoute
  '/admin': typeof AdminIndexRoute
  '/aos': typeof AosIndexRoute
  '/ask': typeof AskIndexRoute
  '/api/public/aos-fp': typeof ApiPublicAosFpRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/tools/sop-edit/$packetId': typeof ToolsSopEditPacketIdRoute
  '/api/public/aos/tier-lookup': typeof ApiPublicAosTierLookupRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calls': typeof CallsRoute
  '/community': typeof CommunityRoute
  '/field-tools': typeof FieldToolsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/handbook': typeof HandbookRoute
  '/hardcore': typeof HardcoreRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/onboarding': typeof OnboardingRoute
  '/operating-playbook': typeof OperatingPlaybookRoute
  '/overwatch': typeof OverwatchRoute
  '/replays': typeof ReplaysRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scheduler': typeof SchedulerRouteWithChildren
  '/scheduler-field': typeof SchedulerFieldRoute
  '/scheduler-portfolio': typeof SchedulerPortfolioRoute
  '/scheduler-preview': typeof SchedulerPreviewRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/tools': typeof ToolsRouteWithChildren
  '/upgrade': typeof UpgradeRoute
  '/vault': typeof VaultRoute
  '/welcome': typeof WelcomeRoute
  '/work-with-marshall': typeof WorkWithMarshallRoute
  '/admin/announce': typeof AdminAnnounceRoute
  '/admin/backfill': typeof AdminBackfillRoute
  '/admin/email-approvals': typeof AdminEmailApprovalsRoute
  '/admin/handbook': typeof AdminHandbookRoute
  '/admin/intensive-leads': typeof AdminIntensiveLeadsRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/migrate': typeof AdminMigrateRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/qa': typeof AdminQaRoute
  '/admin/topics': typeof AdminTopicsRoute
  '/admin/weekly-move': typeof AdminWeeklyMoveRoute
  '/aos/add-capacity': typeof AosAddCapacityRoute
  '/aos/link': typeof AosLinkRoute
  '/api/ask': typeof ApiAskRoute
  '/api/contract-scan': typeof ApiContractScanRoute
  '/api/owner-plays': typeof ApiOwnerPlaysRoute
  '/api/sop-backlog': typeof ApiSopBacklogRoute
  '/api/sop-draft': typeof ApiSopDraftRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/new': typeof AskNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/scheduler/$projectId': typeof SchedulerProjectIdRoute
  '/tools/cos-navigator': typeof ToolsCosNavigatorRoute
  '/tools/growth-constraint': typeof ToolsGrowthConstraintRoute
  '/tools/owner-dependency': typeof ToolsOwnerDependencyRoute
  '/admin/': typeof AdminIndexRoute
  '/aos/': typeof AosIndexRoute
  '/ask/': typeof AskIndexRoute
  '/api/public/aos-fp': typeof ApiPublicAosFpRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/tools/sop-edit/$packetId': typeof ToolsSopEditPacketIdRoute
  '/api/public/aos/tier-lookup': typeof ApiPublicAosTierLookupRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/calls'
    | '/community'
    | '/field-tools'
    | '/forgot-password'
    | '/handbook'
    | '/hardcore'
    | '/login'
    | '/magic-link'
    | '/onboarding'
    | '/operating-playbook'
    | '/overwatch'
    | '/replays'
    | '/reset-password'
    | '/scheduler'
    | '/scheduler-field'
    | '/scheduler-portfolio'
    | '/scheduler-preview'
    | '/signup'
    | '/templates'
    | '/tools'
    | '/upgrade'
    | '/vault'
    | '/welcome'
    | '/work-with-marshall'
    | '/admin/announce'
    | '/admin/backfill'
    | '/admin/email-approvals'
    | '/admin/handbook'
    | '/admin/intensive-leads'
    | '/admin/library'
    | '/admin/migrate'
    | '/admin/people'
    | '/admin/qa'
    | '/admin/topics'
    | '/admin/weekly-move'
    | '/aos/add-capacity'
    | '/aos/link'
    | '/api/ask'
    | '/api/contract-scan'
    | '/api/owner-plays'
    | '/api/sop-backlog'
    | '/api/sop-draft'
    | '/ask/$threadId'
    | '/ask/new'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/scheduler/$projectId'
    | '/tools/cos-navigator'
    | '/tools/growth-constraint'
    | '/tools/owner-dependency'
    | '/admin/'
    | '/aos/'
    | '/ask/'
    | '/api/public/aos-fp'
    | '/lovable/email/suppression'
    | '/tools/sop-edit/$packetId'
    | '/api/public/aos/tier-lookup'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/calls'
    | '/community'
    | '/field-tools'
    | '/forgot-password'
    | '/handbook'
    | '/hardcore'
    | '/login'
    | '/magic-link'
    | '/onboarding'
    | '/operating-playbook'
    | '/overwatch'
    | '/replays'
    | '/reset-password'
    | '/scheduler'
    | '/scheduler-field'
    | '/scheduler-portfolio'
    | '/scheduler-preview'
    | '/signup'
    | '/templates'
    | '/tools'
    | '/upgrade'
    | '/vault'
    | '/welcome'
    | '/work-with-marshall'
    | '/admin/announce'
    | '/admin/backfill'
    | '/admin/email-approvals'
    | '/admin/handbook'
    | '/admin/intensive-leads'
    | '/admin/library'
    | '/admin/migrate'
    | '/admin/people'
    | '/admin/qa'
    | '/admin/topics'
    | '/admin/weekly-move'
    | '/aos/add-capacity'
    | '/aos/link'
    | '/api/ask'
    | '/api/contract-scan'
    | '/api/owner-plays'
    | '/api/sop-backlog'
    | '/api/sop-draft'
    | '/ask/$threadId'
    | '/ask/new'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/scheduler/$projectId'
    | '/tools/cos-navigator'
    | '/tools/growth-constraint'
    | '/tools/owner-dependency'
    | '/admin'
    | '/aos'
    | '/ask'
    | '/api/public/aos-fp'
    | '/lovable/email/suppression'
    | '/tools/sop-edit/$packetId'
    | '/api/public/aos/tier-lookup'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/calls'
    | '/community'
    | '/field-tools'
    | '/forgot-password'
    | '/handbook'
    | '/hardcore'
    | '/login'
    | '/magic-link'
    | '/onboarding'
    | '/operating-playbook'
    | '/overwatch'
    | '/replays'
    | '/reset-password'
    | '/scheduler'
    | '/scheduler-field'
    | '/scheduler-portfolio'
    | '/scheduler-preview'
    | '/signup'
    | '/templates'
    | '/tools'
    | '/upgrade'
    | '/vault'
    | '/welcome'
    | '/work-with-marshall'
    | '/admin/announce'
    | '/admin/backfill'
    | '/admin/email-approvals'
    | '/admin/handbook'
    | '/admin/intensive-leads'
    | '/admin/library'
    | '/admin/migrate'
    | '/admin/people'
    | '/admin/qa'
    | '/admin/topics'
    | '/admin/weekly-move'
    | '/aos/add-capacity'
    | '/aos/link'
    | '/api/ask'
    | '/api/contract-scan'
    | '/api/owner-plays'
    | '/api/sop-backlog'
    | '/api/sop-draft'
    | '/ask/$threadId'
    | '/ask/new'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/scheduler/$projectId'
    | '/tools/cos-navigator'
    | '/tools/growth-constraint'
    | '/tools/owner-dependency'
    | '/admin/'
    | '/aos/'
    | '/ask/'
    | '/api/public/aos-fp'
    | '/lovable/email/suppression'
    | '/tools/sop-edit/$packetId'
    | '/api/public/aos/tier-lookup'
    | '/api/public/stripe/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CallsRoute: typeof CallsRoute
  CommunityRoute: typeof CommunityRoute
  FieldToolsRoute: typeof FieldToolsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HandbookRoute: typeof HandbookRoute
  HardcoreRoute: typeof HardcoreRoute
  LoginRoute: typeof LoginRoute
  MagicLinkRoute: typeof MagicLinkRoute
  OnboardingRoute: typeof OnboardingRoute
  OperatingPlaybookRoute: typeof OperatingPlaybookRoute
  OverwatchRoute: typeof OverwatchRoute
  ReplaysRoute: typeof ReplaysRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchedulerRoute: typeof SchedulerRouteWithChildren
  SchedulerFieldRoute: typeof SchedulerFieldRoute
  SchedulerPortfolioRoute: typeof SchedulerPortfolioRoute
  SchedulerPreviewRoute: typeof SchedulerPreviewRoute
  SignupRoute: typeof SignupRoute
  TemplatesRoute: typeof TemplatesRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UpgradeRoute: typeof UpgradeRoute
  VaultRoute: typeof VaultRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkWithMarshallRoute: typeof WorkWithMarshallRoute
  AdminAnnounceRoute: typeof AdminAnnounceRoute
  AdminBackfillRoute: typeof AdminBackfillRoute
  AdminEmailApprovalsRoute: typeof AdminEmailApprovalsRoute
  AdminHandbookRoute: typeof AdminHandbookRoute
  AdminIntensiveLeadsRoute: typeof AdminIntensiveLeadsRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminMigrateRoute: typeof AdminMigrateRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminQaRoute: typeof AdminQaRoute
  AdminTopicsRoute: typeof AdminTopicsRoute
  AdminWeeklyMoveRoute: typeof AdminWeeklyMoveRoute
  AosAddCapacityRoute: typeof AosAddCapacityRoute
  AosLinkRoute: typeof AosLinkRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiContractScanRoute: typeof ApiContractScanRoute
  ApiOwnerPlaysRoute: typeof ApiOwnerPlaysRoute
  ApiSopBacklogRoute: typeof ApiSopBacklogRoute
  ApiSopDraftRoute: typeof ApiSopDraftRoute
  AskThreadIdRoute: typeof AskThreadIdRoute
  AskNewRoute: typeof AskNewRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AosIndexRoute: typeof AosIndexRoute
  AskIndexRoute: typeof AskIndexRoute
  ApiPublicAosFpRoute: typeof ApiPublicAosFpRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicAosTierLookupRoute: typeof ApiPublicAosTierLookupRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-marshall': {
      id: '/work-with-marshall'
      path: '/work-with-marshall'
      fullPath: '/work-with-marshall'
      preLoaderRoute: typeof WorkWithMarshallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler-preview': {
      id: '/scheduler-preview'
      path: '/scheduler-preview'
      fullPath: '/scheduler-preview'
      preLoaderRoute: typeof SchedulerPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler-portfolio': {
      id: '/scheduler-portfolio'
      path: '/scheduler-portfolio'
      fullPath: '/scheduler-portfolio'
      preLoaderRoute: typeof SchedulerPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler-field': {
      id: '/scheduler-field'
      path: '/scheduler-field'
      fullPath: '/scheduler-field'
      preLoaderRoute: typeof SchedulerFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replays': {
      id: '/replays'
      path: '/replays'
      fullPath: '/replays'
      preLoaderRoute: typeof ReplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overwatch': {
      id: '/overwatch'
      path: '/overwatch'
      fullPath: '/overwatch'
      preLoaderRoute: typeof OverwatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operating-playbook': {
      id: '/operating-playbook'
      path: '/operating-playbook'
      fullPath: '/operating-playbook'
      preLoaderRoute: typeof OperatingPlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardcore': {
      id: '/hardcore'
      path: '/hardcore'
      fullPath: '/hardcore'
      preLoaderRoute: typeof HardcoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-tools': {
      id: '/field-tools'
      path: '/field-tools'
      fullPath: '/field-tools'
      preLoaderRoute: typeof FieldToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/': {
      id: '/ask/'
      path: '/ask'
      fullPath: '/ask/'
      preLoaderRoute: typeof AskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aos/': {
      id: '/aos/'
      path: '/aos'
      fullPath: '/aos/'
      preLoaderRoute: typeof AosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/owner-dependency': {
      id: '/tools/owner-dependency'
      path: '/owner-dependency'
      fullPath: '/tools/owner-dependency'
      preLoaderRoute: typeof ToolsOwnerDependencyRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/growth-constraint': {
      id: '/tools/growth-constraint'
      path: '/growth-constraint'
      fullPath: '/tools/growth-constraint'
      preLoaderRoute: typeof ToolsGrowthConstraintRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/cos-navigator': {
      id: '/tools/cos-navigator'
      path: '/cos-navigator'
      fullPath: '/tools/cos-navigator'
      preLoaderRoute: typeof ToolsCosNavigatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/scheduler/$projectId': {
      id: '/scheduler/$projectId'
      path: '/$projectId'
      fullPath: '/scheduler/$projectId'
      preLoaderRoute: typeof SchedulerProjectIdRouteImport
      parentRoute: typeof SchedulerRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/new': {
      id: '/ask/new'
      path: '/ask/new'
      fullPath: '/ask/new'
      preLoaderRoute: typeof AskNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/$threadId': {
      id: '/ask/$threadId'
      path: '/ask/$threadId'
      fullPath: '/ask/$threadId'
      preLoaderRoute: typeof AskThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sop-draft': {
      id: '/api/sop-draft'
      path: '/api/sop-draft'
      fullPath: '/api/sop-draft'
      preLoaderRoute: typeof ApiSopDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sop-backlog': {
      id: '/api/sop-backlog'
      path: '/api/sop-backlog'
      fullPath: '/api/sop-backlog'
      preLoaderRoute: typeof ApiSopBacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/owner-plays': {
      id: '/api/owner-plays'
      path: '/api/owner-plays'
      fullPath: '/api/owner-plays'
      preLoaderRoute: typeof ApiOwnerPlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contract-scan': {
      id: '/api/contract-scan'
      path: '/api/contract-scan'
      fullPath: '/api/contract-scan'
      preLoaderRoute: typeof ApiContractScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aos/link': {
      id: '/aos/link'
      path: '/aos/link'
      fullPath: '/aos/link'
      preLoaderRoute: typeof AosLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aos/add-capacity': {
      id: '/aos/add-capacity'
      path: '/aos/add-capacity'
      fullPath: '/aos/add-capacity'
      preLoaderRoute: typeof AosAddCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/weekly-move': {
      id: '/admin/weekly-move'
      path: '/admin/weekly-move'
      fullPath: '/admin/weekly-move'
      preLoaderRoute: typeof AdminWeeklyMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/topics': {
      id: '/admin/topics'
      path: '/admin/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AdminTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/qa': {
      id: '/admin/qa'
      path: '/admin/qa'
      fullPath: '/admin/qa'
      preLoaderRoute: typeof AdminQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/migrate': {
      id: '/admin/migrate'
      path: '/admin/migrate'
      fullPath: '/admin/migrate'
      preLoaderRoute: typeof AdminMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/admin/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/intensive-leads': {
      id: '/admin/intensive-leads'
      path: '/admin/intensive-leads'
      fullPath: '/admin/intensive-leads'
      preLoaderRoute: typeof AdminIntensiveLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/handbook': {
      id: '/admin/handbook'
      path: '/admin/handbook'
      fullPath: '/admin/handbook'
      preLoaderRoute: typeof AdminHandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email-approvals': {
      id: '/admin/email-approvals'
      path: '/admin/email-approvals'
      fullPath: '/admin/email-approvals'
      preLoaderRoute: typeof AdminEmailApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backfill': {
      id: '/admin/backfill'
      path: '/admin/backfill'
      fullPath: '/admin/backfill'
      preLoaderRoute: typeof AdminBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announce': {
      id: '/admin/announce'
      path: '/admin/announce'
      fullPath: '/admin/announce'
      preLoaderRoute: typeof AdminAnnounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/sop-edit/$packetId': {
      id: '/tools/sop-edit/$packetId'
      path: '/sop-edit/$packetId'
      fullPath: '/tools/sop-edit/$packetId'
      preLoaderRoute: typeof ToolsSopEditPacketIdRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/aos-fp': {
      id: '/api/public/aos-fp'
      path: '/api/public/aos-fp'
      fullPath: '/api/public/aos-fp'
      preLoaderRoute: typeof ApiPublicAosFpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/aos/tier-lookup': {
      id: '/api/public/aos/tier-lookup'
      path: '/api/public/aos/tier-lookup'
      fullPath: '/api/public/aos/tier-lookup'
      preLoaderRoute: typeof ApiPublicAosTierLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SchedulerRouteChildren {
  SchedulerProjectIdRoute: typeof SchedulerProjectIdRoute
}

const SchedulerRouteChildren: SchedulerRouteChildren = {
  SchedulerProjectIdRoute: SchedulerProjectIdRoute,
}

const SchedulerRouteWithChildren = SchedulerRoute._addFileChildren(
  SchedulerRouteChildren,
)

interface ToolsRouteChildren {
  ToolsCosNavigatorRoute: typeof ToolsCosNavigatorRoute
  ToolsGrowthConstraintRoute: typeof ToolsGrowthConstraintRoute
  ToolsOwnerDependencyRoute: typeof ToolsOwnerDependencyRoute
  ToolsSopEditPacketIdRoute: typeof ToolsSopEditPacketIdRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsCosNavigatorRoute: ToolsCosNavigatorRoute,
  ToolsGrowthConstraintRoute: ToolsGrowthConstraintRoute,
  ToolsOwnerDependencyRoute: ToolsOwnerDependencyRoute,
  ToolsSopEditPacketIdRoute: ToolsSopEditPacketIdRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CallsRoute: CallsRoute,
  CommunityRoute: CommunityRoute,
  FieldToolsRoute: FieldToolsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HandbookRoute: HandbookRoute,
  HardcoreRoute: HardcoreRoute,
  LoginRoute: LoginRoute,
  MagicLinkRoute: MagicLinkRoute,
  OnboardingRoute: OnboardingRoute,
  OperatingPlaybookRoute: OperatingPlaybookRoute,
  OverwatchRoute: OverwatchRoute,
  ReplaysRoute: ReplaysRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchedulerRoute: SchedulerRouteWithChildren,
  SchedulerFieldRoute: SchedulerFieldRoute,
  SchedulerPortfolioRoute: SchedulerPortfolioRoute,
  SchedulerPreviewRoute: SchedulerPreviewRoute,
  SignupRoute: SignupRoute,
  TemplatesRoute: TemplatesRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UpgradeRoute: UpgradeRoute,
  VaultRoute: VaultRoute,
  WelcomeRoute: WelcomeRoute,
  WorkWithMarshallRoute: WorkWithMarshallRoute,
  AdminAnnounceRoute: AdminAnnounceRoute,
  AdminBackfillRoute: AdminBackfillRoute,
  AdminEmailApprovalsRoute: AdminEmailApprovalsRoute,
  AdminHandbookRoute: AdminHandbookRoute,
  AdminIntensiveLeadsRoute: AdminIntensiveLeadsRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminMigrateRoute: AdminMigrateRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminQaRoute: AdminQaRoute,
  AdminTopicsRoute: AdminTopicsRoute,
  AdminWeeklyMoveRoute: AdminWeeklyMoveRoute,
  AosAddCapacityRoute: AosAddCapacityRoute,
  AosLinkRoute: AosLinkRoute,
  ApiAskRoute: ApiAskRoute,
  ApiContractScanRoute: ApiContractScanRoute,
  ApiOwnerPlaysRoute: ApiOwnerPlaysRoute,
  ApiSopBacklogRoute: ApiSopBacklogRoute,
  ApiSopDraftRoute: ApiSopDraftRoute,
  AskThreadIdRoute: AskThreadIdRoute,
  AskNewRoute: AskNewRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  AdminIndexRoute: AdminIndexRoute,
  AosIndexRoute: AosIndexRoute,
  AskIndexRoute: AskIndexRoute,
  ApiPublicAosFpRoute: ApiPublicAosFpRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicAosTierLookupRoute: ApiPublicAosTierLookupRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
